# The port to listen to for HTTP requests
server:
    port: 8080
    host: "0.0.0.0"

scan:
    # The script that will be given a file as its first parameter
    script: './example.sh'
    # The temporary directory to use
    tempDirectory: '/tmp'
    # The base URL of the homeserver to download media from
    baseUrl: 'https://matrix.org'
    # If set to true, effectively set baseUrl to
    #   "https://$domain"
    #   where $domain is the domain part of the requested media.
    #
    # This should only be used when it is preferable not to download
    # media through the normal route: via a single (and federated)
    # homeserver.
    #
    # directDownload: false

# Optional. A command to execute when unlinking files from the file
# system instead of using node's fs.unlink. When executed, the first
# argument to the command will be the path of the file being
# removed.
# Docker note: the `srm` utility is already bundled into the base Docker image
# built by the project. See `Dockerfile` for additional notes.
#
altRemovalCmd: 'srm'
