name: Unit tests
on:
  # Trigger the workflow on a pull request,, or when committing
  # 'main' branch
  pull_request:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Retrieve dependencies and set up the test environment
      - run: make build

      # Run the tests
      - run: make test
